export const content = {
  en: {
    dir: 'ltr',
    nav: { home: 'Home', work: 'Work', exp: 'Experience', photos: 'Photography', articles: 'Articles', about: 'About', contact: 'Contact' },
    langBtn: 'العربية',
    hero: {
      kicker: 'Syrian Journalist — 14 Years in the Field',
      name1: 'HAIDAR',
      name2: 'MUSTAFA',
      tagline: 'Covering conflicts, politics, and human stories across the Middle East.',
      cta1: 'View Work',
      cta2: 'Contact',
    },
    ticker: ['Field Correspondent', 'Reuters', 'AFP', 'Xinhua', 'Conflict Reporting', 'News Anchor', 'Syria · Lebanon · Iraq', 'Photojournalist'],
    stats: [
      { n: '14+', l: 'Years Experience' },
      { n: '3', l: 'Countries' },
      { n: '12', l: 'Media Orgs' },
      { n: '4', l: 'Roles' },
      { n: '∞', l: 'Human Stories' },
    ],
    showreel: {
      label: 'Showreel',
      caption: 'FIELD REPORTING · LIVE BROADCASTING · CONFLICT COVERAGE · PHOTOJOURNALISM',
      tags: ['Field Reporting', 'Live Broadcasting', 'News Anchoring', 'Photography', 'Conflict', 'Humanitarian', 'International'],
      videoUrl: '',
    },
    orgsLabel: 'Media Organizations',
    orgs: [
      { name: 'Reuters', wire: true },
      { name: 'AFP', wire: true },
      { name: 'Xinhua', wire: true },
      { name: 'Viory' },
      { name: 'Ana Sooria TV' },
      { name: 'Alghad TV' },
      { name: 'Syrian News Channel' },
      { name: 'Raseef22' },
      { name: 'The Cradle' },
      { name: 'Syria Untold' },
      { name: 'Cham Times' },
    ],
    work: {
      title: 'Featured Reports',
      sub: 'Selected Field Work',
      reports: [
        {
          src: 'Xinhua',
          title: 'Children of Salma Learn in Tents Built on the Ruins of War',
          desc: 'Field report from Latakia countryside — education continuing despite destruction left by years of conflict.',
          link: 'http://arabic.china.org.cn/txt/2025-10/20/content_118131531.htm',
          linkLabel: 'Read Report',
          image: '',
        },
        {
          src: 'Viory',
          title: 'Syrian Beekeeper Loses 70%+ of Apiaries in Latakia Wildfires',
          desc: 'A human-centered story on the economic and environmental impact of the devastating 2025 wildfires.',
          link: 'https://www.viory.video/en/videos/a3415_12072025/loss-worth-tens-of-millions-syrian-beekeeper-loses-more-than-70-of-apiaries-in-wildfire-ravaged-latakia-forests',
          linkLabel: 'Watch Report',
          image: '',
        },
        {
          src: 'Viory',
          title: 'Charity Kitchens Feed Thousands After Syria Earthquake',
          desc: 'Humanitarian coverage documenting relief operations across Latakia in the aftermath of the 2023 earthquake.',
          link: 'https://www.viory.video/en/videos/a3015_19022023',
          linkLabel: 'Watch Report',
          image: '',
        },
        {
          src: 'Reuters',
          title: "Life on Syria's Coast After Political Transition",
          desc: "Reporting on daily life, security, and social changes during Syria's major period of political transformation.",
          link: 'https://youtu.be/9HoBeXiR0QA',
          linkLabel: 'Watch Report',
          image: '',
        },
      ],
    },
    coverage: {
      title: 'Major Coverage',
      sub: 'Key Events · Field Presence',
      items: [
        {
          name: 'Iraqi Protests',
          year: '2019',
          desc: "Field reporting from Baghdad's Tahrir Square — demonstrations, civil activism, and political developments during the nationwide protest movement.",
          links: [
            { label: 'Tahrir Square Rally', url: 'https://www.viory.video/en/videos/a3064_20122019/iraq-anti-govt-protesters-rally-into-night-in-baghdad-s-tahrir-square' },
            { label: 'Baghdad Freestyle', url: 'https://www.viory.video/en/videos/a3009_31122019' },
          ],
        },
        {
          name: 'Turkey-Syria Earthquake',
          year: '2023',
          desc: 'Field and humanitarian coverage — rescue operations, relief efforts, and the human cost across affected communities.',
          links: [
            { label: 'Report 1', url: 'https://www.youtube.com/watch?v=qD1O930DzyI' },
            { label: 'Report 2', url: 'https://www.youtube.com/watch?v=aPqB7lA-cps' },
            { label: 'Charity Kitchens', url: 'https://www.viory.video/en/videos/a3015_19022023' },
          ],
        },
        {
          name: 'Political Transition in Syria',
          year: '2024–2025',
          desc: "Contributed to Reuters and international coverage of Latakia and Syria's coastal region during major political and security transformation.",
          links: [
            { label: 'Reuters — UN Report', url: 'https://www.reuters.com/world/middle-east/un-says-entire-families-killed-syria-military-operation-2025-03-11/' },
            { label: 'Report 1', url: 'https://www.youtube.com/watch?v=MjvUS6Y8Nlg' },
            { label: 'Report 2', url: 'https://www.youtube.com/watch?v=itNeXenRjo4' },
          ],
        },
        {
          name: 'Latakia Wildfires',
          year: '2025',
          desc: 'Emergency field reporting — response operations, environmental damage, and community impact during the 2025 wildfire crisis.',
          links: [
            { label: 'Firefighters Join', url: 'https://www.viory.video/en/videos/a3458_10072025' },
            { label: 'Beekeeper Story', url: 'https://www.viory.video/en/videos/a3415_12072025' },
          ],
        },
      ],
    },
    experience: {
      title: 'Experience',
      sub: '14 Years · 8 Organizations',
      items: [
        {
          years: '2019 — Present',
          org: 'Viory',
          role: 'Stringer & Regional Coordinator',
          bullets: [
            'Field production across Syria, Lebanon, Iraq',
            'Political, conflict, and humanitarian reporting',
            'Coordinating 50+ field journalists across Lebanon, Iraq, Libya',
            'International news coverage and multimedia production',
          ],
          links: [
            { label: 'Latakia Wildfires', url: 'https://www.viory.video/en/videos/a3458_10072025' },
            { label: 'Beekeeper Story', url: 'https://www.viory.video/en/videos/a3415_12072025' },
          ],
        },
        {
          years: '2020 — Present',
          org: 'Reuters · AFP · Xinhua',
          role: 'Freelance Photojournalist',
          bullets: [
            'International wire agency photojournalism',
            'Conflict, protest, and humanitarian photography',
            "Syria's political transition and coastal developments",
          ],
          links: [
            { label: 'Reuters Connect', url: 'https://www.reutersconnect.com/item/people-queue-in-front-of-a-bakery-in-latakia/dGFnOnJldXRlcnMuY29tLDIwMjU6bmV3c21sX1JDMlc5REE0WUtaMQ' },
            { label: 'Xinhua', url: 'https://arabic.news.cn/20251228/eb603bcec09f47d1a872f0ee5d4edaa5/c.html' },
          ],
        },
        {
          years: '2024 — Present',
          org: 'Ana Sooria TV',
          role: 'Reporter',
          bullets: ['Television reporting and live broadcasts', 'Breaking news coverage and human-interest stories'],
          links: [
            { label: 'Report 1', url: 'https://www.youtube.com/watch?v=PhL3R_hAyDo' },
            { label: 'Report 2', url: 'https://www.youtube.com/watch?v=qFJTfyLx-q0' },
            { label: 'Report 3', url: 'https://www.youtube.com/watch?v=_iH24Y8Ev-A' },
          ],
        },
        {
          years: '2022 — 2024',
          org: 'Alghad TV',
          role: 'Journalist & Field Correspondent',
          bullets: ['Television reporting and live coverage', 'Political, social, and human-interest reporting'],
          links: [
            { label: 'Report 1', url: 'https://www.youtube.com/watch?v=x_Y5GXrGxLE' },
            { label: 'Report 2', url: 'https://www.youtube.com/watch?v=xsDjCgYjtmU' },
          ],
        },
        {
          years: '2020 — 2024',
          org: 'Syrian News Channel',
          role: 'News Anchor, Reporter & Program Presenter',
          bullets: ['Host of Al-Badil (The Alternative) program', 'News anchoring, live presentation, field and studio reporting'],
          links: [
            { label: 'Al-Badil Ep. 1', url: 'https://www.youtube.com/watch?v=lo-Yae8_Vsw' },
            { label: 'Al-Badil Ep. 2', url: 'https://www.youtube.com/watch?v=urbcgLvUYjE' },
          ],
        },
        {
          years: '2020 — 2022',
          org: 'Cham Times Media Network',
          role: 'Editor-in-Chief',
          bullets: ['Editorial leadership and newsroom management', 'Content strategy and team supervision'],
          links: [],
        },
        {
          years: '2012 — 2015',
          org: 'Sama TV',
          role: 'Editor',
          bullets: ['News editing and editorial production', 'Television newsroom operations'],
          links: [],
        },
      ],
    },
    photography: {
      title: 'Photography',
      sub: 'Reuters · AFP · Xinhua · Field Work',
      allLabel: 'All',
      categories: [
        {
          id: 'conflict',
          label: 'Conflict',
          photos: [
            { src: '', caption: 'Syria Coast, 2025' },
            { src: '', caption: 'Iraq Protests, Baghdad 2019' },
          ],
        },
        {
          id: 'humanitarian',
          label: 'Humanitarian',
          photos: [
            { src: '', caption: 'Earthquake Relief Operations, 2023' },
            { src: '', caption: 'Salma School Tents, Latakia' },
          ],
        },
        {
          id: 'politics',
          label: 'Politics',
          photos: [
            { src: '', caption: 'Arab League Summit' },
            { src: '', caption: 'Syria Political Transition, 2024' },
          ],
        },
        {
          id: 'breaking',
          label: 'Breaking News',
          photos: [
            { src: '', caption: 'Latakia Wildfires, 2025' },
            { src: '', caption: 'Firefighters Arrive on Scene' },
          ],
        },
        {
          id: 'daily',
          label: 'Daily Life',
          photos: [
            { src: '', caption: 'Bakery Queue, Latakia' },
          ],
        },
      ],
    },
    articles: {
      title: 'Articles',
      sub: 'Raseef22 · The Cradle · Written Work',
      items: [
        { pub: 'Raseef22', title: 'Youssef Guards His Village in Dahok — Alone, After Everyone Left', excerpt: 'A human story of abandonment, resilience, and the weight of staying when everyone else has gone.' },
        { pub: 'Raseef22', title: "The Poverty Oven — Latakia Mountain Residents Work for Others' Comfort", excerpt: 'An economic field story on how mountain communities survive by serving wealthier neighbors.' },
        { pub: 'Raseef22', title: 'No Voice But the Voice of Criticism — Syria Cuts Support from Social Classes', excerpt: 'Reporting on economic and social policy shifts amid political change in Syria.' },
        { pub: 'The Cradle', title: 'Articles Archive — The Cradle Arabic', excerpt: 'Contributing writer covering Syrian affairs and regional geopolitics.' },
      ],
    },
    about: {
      title: 'About',
      sub: 'Journalist · Syria',
      langLabel: 'Languages',
      langs: [
        { name: 'Arabic', level: 'Native' },
        { name: 'English', level: 'Professional' },
      ],
      bio: [
        'For more than fourteen years, I have worked across different areas of journalism — television reporting, news anchoring, editorial leadership, photojournalism, and multimedia storytelling.',
        'Throughout my career, I have covered major political developments, conflicts, humanitarian crises, and social issues across Syria, Lebanon, and Iraq. My work has appeared through local, regional, and international media organizations.',
        'In addition to journalism, I have studied English Translation, Politics, and International Relations, and have completed extensive professional training in journalism, verification, human rights, safety, and media development.',
      ],
      skillsLabel: 'Skills',
      skills: [
        'Field Reporting & Live Broadcasting',
        'Conflict & Crisis Reporting',
        'News Production & Editorial Management',
        'News Anchoring',
        'Multimedia Storytelling',
        'Photojournalism',
        'Fact-Checking & Verification',
        'Team Leadership',
      ],
      certsLabel: 'Training & Certifications',
      certs: [
        { name: 'HEFAT — Hostile Environment First Aid', org: 'Samir Kassir Foundation' },
        { name: 'AI-Generated Content Verification', org: 'AFP' },
        { name: 'Information Verification', org: 'Sawab Platform' },
        { name: 'Train the Trainers', org: 'DW Akademie' },
        { name: 'Data Journalism', org: 'Friedrich Naumann Foundation' },
        { name: 'International Human Rights Course', org: 'Jinan University · IIHR' },
        { name: 'Social Media Solutions', org: 'ICFJ · SMEX' },
        { name: 'News and Program Presentation', org: 'Syrian International Academy' },
      ],
      previewBtn: 'Full Bio →',
    },
    contact: {
      title: 'Contact',
      sub: 'Syria — Damascus & Latakia',
      headline1: "Let's",
      headline2: 'Work',
      headline3: 'Together',
      info: [
        { label: 'Email', value: 'Haidarmustafa.media@gmail.com' },
        { label: 'Phone', value: '+963 931 600 388' },
        { label: 'WhatsApp', value: '+963 994 991 566' },
        { label: 'LinkedIn', value: 'haidar-mustafa-5a6b26174' },
        { label: 'Location', value: 'Syria — Damascus & Latakia' },
      ],
      availLabel: 'Available For',
      avail: ['Reporting Assignments', 'Field Production', 'Editorial Consulting', 'Multimedia Projects', 'International Collaborations'],
      formLabel: 'Send a Message',
      labels: { name: 'Name', email: 'Email', org: 'Organization', msg: 'Message' },
      placeholders: { name: 'Your name', email: 'your@email.com', org: 'Media outlet or organization', msg: 'Tell me about the assignment or collaboration...' },
      submit: 'Send Message',
      previewBtn: 'Send a Message →',
    },
    footer: { brand: 'Haidar Mustafa · حيدر مصطفى', copy: '© 2025 · Journalist · Syria' },
  },

  ar: {
    dir: 'rtl',
    nav: { home: 'الرئيسية', work: 'الأعمال', exp: 'الخبرات', photos: 'التصوير', articles: 'المقالات', about: 'نبذة', contact: 'تواصل' },
    langBtn: 'English',
    hero: {
      kicker: 'صحفي سوري — 14 عاماً في الميدان',
      name1: 'حيدر',
      name2: 'مصطفى',
      tagline: 'تغطية الصراعات والسياسة والقصص الإنسانية عبر الشرق الأوسط.',
      cta1: 'عرض الأعمال',
      cta2: 'تواصل معي',
    },
    ticker: ['مراسل ميداني', 'رويترز', 'أ.ف.ب', 'شينخوا', 'تغطية النزاعات', 'مذيع أخبار', 'سوريا · لبنان · العراق', 'مصوّر صحفي'],
    stats: [
      { n: '14+', l: 'سنة خبرة' },
      { n: '3', l: 'دول' },
      { n: '12', l: 'مؤسسة إعلامية' },
      { n: '4', l: 'أدوار' },
      { n: '∞', l: 'قصة إنسانية' },
    ],
    showreel: {
      label: 'الشوريل',
      caption: 'تقارير ميدانية · بث مباشر · تغطية نزاعات · تصوير صحفي',
      tags: ['تقارير ميدانية', 'بث مباشر', 'تقديم الأخبار', 'التصوير الصحفي', 'تغطية النزاعات', 'التغطية الإنسانية', 'إعلام دولي'],
      videoUrl: '',
    },
    orgsLabel: 'المؤسسات الإعلامية',
    orgs: [
      { name: 'Reuters', wire: true },
      { name: 'AFP', wire: true },
      { name: 'Xinhua', wire: true },
      { name: 'Viory' },
      { name: 'Ana Sooria TV' },
      { name: 'Alghad TV' },
      { name: 'Syrian News Channel' },
      { name: 'Raseef22' },
      { name: 'The Cradle' },
      { name: 'Syria Untold' },
      { name: 'Cham Times' },
    ],
    work: {
      title: 'تقارير مختارة',
      sub: 'أعمال ميدانية',
      reports: [
        {
          src: 'Xinhua',
          title: 'أطفال سلمى يتعلمون في خيام بنيت على أنقاض الحرب',
          desc: 'تقرير ميداني من ريف اللاذقية — التعليم مستمر رغم الدمار الذي خلفته سنوات الصراع.',
          link: 'http://arabic.china.org.cn/txt/2025-10/20/content_118131531.htm',
          linkLabel: 'قراءة التقرير',
          image: '',
        },
        {
          src: 'Viory',
          title: 'نحّال سوري يخسر أكثر من 70% من مناحله في حرائق اللاذقية',
          desc: 'قصة إنسانية عن الأثر الاقتصادي والبيئي لحرائق 2025 المدمرة.',
          link: 'https://www.viory.video/en/videos/a3415_12072025/loss-worth-tens-of-millions-syrian-beekeeper-loses-more-than-70-of-apiaries-in-wildfire-ravaged-latakia-forests',
          linkLabel: 'مشاهدة التقرير',
          image: '',
        },
        {
          src: 'Viory',
          title: 'مطابخ خيرية تطعم الآلاف بعد زلزال سوريا',
          desc: 'تغطية إنسانية توثّق عمليات الإغاثة في اللاذقية بعد زلزال 2023.',
          link: 'https://www.viory.video/en/videos/a3015_19022023',
          linkLabel: 'مشاهدة التقرير',
          image: '',
        },
        {
          src: 'Reuters',
          title: 'الحياة على الساحل السوري بعد التحول السياسي',
          desc: 'تغطية للحياة اليومية والأمن والتغيرات الاجتماعية خلال فترة التحول السياسي الكبرى في سوريا.',
          link: 'https://youtu.be/9HoBeXiR0QA',
          linkLabel: 'مشاهدة التقرير',
          image: '',
        },
      ],
    },
    coverage: {
      title: 'تغطيات كبرى',
      sub: 'أبرز الأحداث · حضور ميداني',
      items: [
        {
          name: 'احتجاجات العراق',
          year: '2019',
          desc: 'تغطية ميدانية من ساحة التحرير في بغداد — المظاهرات والنشاط المدني والتطورات السياسية خلال حركة الاحتجاج الواسعة.',
          links: [
            { label: 'مظاهرة ساحة التحرير', url: 'https://www.viory.video/en/videos/a3064_20122019/iraq-anti-govt-protesters-rally-into-night-in-baghdad-s-tahrir-square' },
            { label: 'فريستايل بغداد', url: 'https://www.viory.video/en/videos/a3009_31122019' },
          ],
        },
        {
          name: 'زلزال تركيا وسوريا',
          year: '2023',
          desc: 'تغطية ميدانية وإنسانية — عمليات الإنقاذ وجهود الإغاثة والتكلفة الإنسانية في المجتمعات المتضررة.',
          links: [
            { label: 'تقرير 1', url: 'https://www.youtube.com/watch?v=qD1O930DzyI' },
            { label: 'تقرير 2', url: 'https://www.youtube.com/watch?v=aPqB7lA-cps' },
            { label: 'مطابخ خيرية', url: 'https://www.viory.video/en/videos/a3015_19022023' },
          ],
        },
        {
          name: 'التحول السياسي في سوريا',
          year: '2024–2025',
          desc: 'مساهمة في تغطية رويترز والإعلام الدولي للاذقية والساحل السوري خلال فترة التحول السياسي والأمني الكبرى.',
          links: [
            { label: 'رويترز — تقرير الأمم المتحدة', url: 'https://www.reuters.com/world/middle-east/un-says-entire-families-killed-syria-military-operation-2025-03-11/' },
            { label: 'تقرير 1', url: 'https://www.youtube.com/watch?v=MjvUS6Y8Nlg' },
            { label: 'تقرير 2', url: 'https://www.youtube.com/watch?v=itNeXenRjo4' },
          ],
        },
        {
          name: 'حرائق اللاذقية',
          year: '2025',
          desc: 'تغطية ميدانية طارئة — عمليات الاستجابة والأضرار البيئية وتأثيرها على المجتمعات المحلية خلال أزمة حرائق 2025.',
          links: [
            { label: 'انضمام رجال الإطفاء', url: 'https://www.viory.video/en/videos/a3458_10072025' },
            { label: 'قصة النحّال', url: 'https://www.viory.video/en/videos/a3415_12072025' },
          ],
        },
      ],
    },
    experience: {
      title: 'الخبرات',
      sub: '14 عاماً · 8 مؤسسات',
      items: [
        {
          years: '2019 — حتى الآن',
          org: 'Viory',
          role: 'مراسل ومنسق إقليمي',
          bullets: [
            'إنتاج ميداني عبر سوريا ولبنان والعراق',
            'تغطية سياسية وإنسانية وتغطية النزاعات',
            'تنسيق أكثر من 50 صحفياً ميدانياً عبر لبنان والعراق وليبيا',
            'تغطية إخبارية دولية وإنتاج متعدد الوسائط',
          ],
          links: [
            { label: 'حرائق اللاذقية', url: 'https://www.viory.video/en/videos/a3458_10072025' },
            { label: 'قصة النحّال', url: 'https://www.viory.video/en/videos/a3415_12072025' },
          ],
        },
        {
          years: '2020 — حتى الآن',
          org: 'رويترز · أ.ف.ب · شينخوا',
          role: 'مصوّر صحفي مستقل',
          bullets: [
            'تصوير صحفي لوكالات الأنباء الدولية',
            'تصوير النزاعات والاحتجاجات والقضايا الإنسانية',
            'التحول السياسي في سوريا والتطورات الساحلية',
          ],
          links: [
            { label: 'Reuters Connect', url: 'https://www.reutersconnect.com/item/people-queue-in-front-of-a-bakery-in-latakia/dGFnOnJldXRlcnMuY29tLDIwMjU6bmV3c21sX1JDMlc5REE0WUtaMQ' },
            { label: 'شينخوا', url: 'https://arabic.news.cn/20251228/eb603bcec09f47d1a872f0ee5d4edaa5/c.html' },
          ],
        },
        {
          years: '2024 — حتى الآن',
          org: 'Ana Sooria TV',
          role: 'مراسل',
          bullets: ['تغطية تلفزيونية وبث مباشر', 'تغطية الأخبار العاجلة والقصص الإنسانية'],
          links: [
            { label: 'تقرير 1', url: 'https://www.youtube.com/watch?v=PhL3R_hAyDo' },
            { label: 'تقرير 2', url: 'https://www.youtube.com/watch?v=qFJTfyLx-q0' },
            { label: 'تقرير 3', url: 'https://www.youtube.com/watch?v=_iH24Y8Ev-A' },
          ],
        },
        {
          years: '2022 — 2024',
          org: 'Alghad TV',
          role: 'صحفي ومراسل ميداني',
          bullets: ['تغطية تلفزيونية وبث مباشر', 'تغطية سياسية واجتماعية وإنسانية'],
          links: [
            { label: 'تقرير 1', url: 'https://www.youtube.com/watch?v=x_Y5GXrGxLE' },
            { label: 'تقرير 2', url: 'https://www.youtube.com/watch?v=xsDjCgYjtmU' },
          ],
        },
        {
          years: '2020 — 2024',
          org: 'القناة السورية الإخبارية',
          role: 'مذيع ومراسل ومقدم برامج',
          bullets: ['تقديم برنامج "البديل"', 'تقديم نشرات إخبارية وبث مباشر وتغطية ميدانية واستوديو'],
          links: [
            { label: 'البديل ح1', url: 'https://www.youtube.com/watch?v=lo-Yae8_Vsw' },
            { label: 'البديل ح2', url: 'https://www.youtube.com/watch?v=urbcgLvUYjE' },
          ],
        },
        {
          years: '2020 — 2022',
          org: 'شبكة شام تايمز الإعلامية',
          role: 'رئيس تحرير',
          bullets: ['قيادة تحريرية وإدارة غرفة الأخبار', 'استراتيجية المحتوى والإشراف على الفريق'],
          links: [],
        },
        {
          years: '2012 — 2015',
          org: 'Sama TV',
          role: 'محرر',
          bullets: ['تحرير الأخبار والإنتاج التحريري', 'عمليات غرفة الأخبار التلفزيونية'],
          links: [],
        },
      ],
    },
    photography: {
      title: 'التصوير الصحفي',
      sub: 'رويترز · أ.ف.ب · شينخوا · أعمال ميدانية',
      allLabel: 'الكل',
      categories: [
        {
          id: 'conflict',
          label: 'نزاعات',
          photos: [
            { src: '', caption: 'الساحل السوري، 2025' },
            { src: '', caption: 'احتجاجات العراق، بغداد 2019' },
          ],
        },
        {
          id: 'humanitarian',
          label: 'إنسانية',
          photos: [
            { src: '', caption: 'عمليات إغاثة الزلزال، 2023' },
            { src: '', caption: 'خيام مدرسة سلمى، اللاذقية' },
          ],
        },
        {
          id: 'politics',
          label: 'سياسة',
          photos: [
            { src: '', caption: 'قمة الجامعة العربية' },
            { src: '', caption: 'التحول السياسي في سوريا، 2024' },
          ],
        },
        {
          id: 'breaking',
          label: 'أخبار عاجلة',
          photos: [
            { src: '', caption: 'حرائق اللاذقية، 2025' },
            { src: '', caption: 'وصول رجال الإطفاء' },
          ],
        },
        {
          id: 'daily',
          label: 'حياة يومية',
          photos: [
            { src: '', caption: 'طابور الفرن، اللاذقية' },
          ],
        },
      ],
    },
    articles: {
      title: 'المقالات',
      sub: 'رصيف22 · ذا كريدل · كتابات',
      items: [
        { pub: 'Raseef22', title: 'يوسف يحرس قريته في دهوك — وحيداً، بعد رحيل الجميع', excerpt: 'قصة إنسانية عن الهجران والصمود وثقل البقاء عندما يرحل الجميع.' },
        { pub: 'Raseef22', title: 'فرن الفقر لم يعد كذلك — سكان جبال اللاذقية يعملون من أجل راحة الآخرين', excerpt: 'قصة اقتصادية ميدانية عن كيفية بقاء المجتمعات الجبلية عبر خدمة الجيران الأكثر ثراءً.' },
        { pub: 'Raseef22', title: 'لا صوت يعلو فوق صوت النقد — الحكومة السورية تقطع الدعم عن الطبقات الاجتماعية', excerpt: 'تغطية للتحولات في السياسة الاقتصادية والاجتماعية وسط التغيير السياسي في سوريا.' },
        { pub: 'The Cradle', title: 'أرشيف المقالات — ذا كريدل بالعربية', excerpt: 'كاتب مساهم يغطي الشأن السوري والجيوسياسة الإقليمية.' },
      ],
    },
    about: {
      title: 'نبذة',
      sub: 'صحفي · سوريا',
      langLabel: 'اللغات',
      langs: [
        { name: 'العربية', level: 'لغة أم' },
        { name: 'الإنكليزية', level: 'احترافية' },
      ],
      bio: [
        'على مدى أكثر من أربعة عشر عاماً، عملت في مجالات مختلفة من الصحافة — التغطية التلفزيونية، تقديم النشرات الإخبارية، القيادة التحريرية، التصوير الصحفي، والسرد متعدد الوسائط.',
        'خلال مسيرتي، غطّيت تطورات سياسية كبرى ونزاعات وأزمات إنسانية وقضايا اجتماعية عبر سوريا ولبنان والعراق. ظهر عملي عبر مؤسسات إعلامية محلية وإقليمية ودولية.',
        'إضافة إلى الصحافة، درست الترجمة الإنكليزية والعلوم السياسية والعلاقات الدولية، وأكملت تدريبات مهنية واسعة في الصحافة والتحقق وحقوق الإنسان والسلامة وتطوير الإعلام.',
      ],
      skillsLabel: 'المهارات',
      skills: [
        'التغطية الميدانية والبث المباشر',
        'تغطية النزاعات والأزمات',
        'الإنتاج الإخباري والإدارة التحريرية',
        'تقديم النشرات الإخبارية',
        'السرد متعدد الوسائط',
        'التصوير الصحفي',
        'التحقق من المعلومات',
        'قيادة الفريق',
      ],
      certsLabel: 'التدريب والشهادات',
      certs: [
        { name: 'HEFAT — الإسعافات الأولية في البيئات الخطرة', org: 'مؤسسة سمير قصير' },
        { name: 'التحقق من المحتوى المولّد بالذكاء الاصطناعي', org: 'AFP' },
        { name: 'التحقق من المعلومات', org: 'منصة سواب' },
        { name: 'تدريب المدربين', org: 'DW Akademie' },
        { name: 'صحافة البيانات', org: 'مؤسسة فريدريش ناومان' },
        { name: 'دورة حقوق الإنسان الدولية', org: 'جامعة الجنان · IIHR' },
        { name: 'حلول وسائل التواصل الاجتماعي', org: 'ICFJ · SMEX' },
        { name: 'تقديم الأخبار والبرامج', org: 'الأكاديمية السورية الدولية' },
      ],
      previewBtn: '← السيرة الكاملة',
    },
    contact: {
      title: 'تواصل',
      sub: 'سوريا — دمشق واللاذقية',
      headline1: 'لنعمل',
      headline2: '',
      headline3: 'معاً',
      info: [
        { label: 'البريد', value: 'Haidarmustafa.media@gmail.com' },
        { label: 'هاتف', value: '+963 931 600 388' },
        { label: 'واتساب', value: '+963 994 991 566' },
        { label: 'لينكدإن', value: 'haidar-mustafa-5a6b26174' },
        { label: 'الموقع', value: 'سوريا — دمشق واللاذقية' },
      ],
      availLabel: 'متاح لـ',
      avail: ['مهام تقارير', 'إنتاج ميداني', 'استشارات تحريرية', 'مشاريع متعددة الوسائط', 'تعاون دولي'],
      formLabel: 'أرسل رسالة',
      labels: { name: 'الاسم', email: 'البريد الإلكتروني', org: 'المؤسسة', msg: 'الرسالة' },
      placeholders: { name: 'اسمك', email: 'your@email.com', org: 'المؤسسة الإعلامية', msg: 'أخبرني عن المهمة أو التعاون...' },
      submit: 'إرسال',
      previewBtn: '← أرسل رسالة',
    },
    footer: { brand: 'حيدر مصطفى · Haidar Mustafa', copy: '© 2025 · صحفي · سوريا' },
  },
}
